# config.yaml
training:
  n_epochs: 2_000
  batch_size: 2500
  learning_rate : 0.001
  device: 'cuda:3'
  save_interval: 1000
  checkpoint_dir: 'models/'

model:
  input_dim: 2
  hidden_dim: 128
  num_layers: 4
  activation_fn: 'tanh' # or 'tanh' or 'softplus' or 'relu' or 'sin'
  time_varying: True

data:
  type: 'gaussian1' # 
  #swissroll,circles,rings,moons,8gaussians,8gaussiansv2,8gaussiansv3,
  #4gaussians,gaussian0,gaussian1, gaussian0_d,gaussian1_d,gauss0_opinion_2d
  # gauss1_opinion_2d, gauss0_opinion_1000d, gauss1_opinion_1000d
  total_data: 15_000
  