data:
  total_data: 100000
  type: gauss0_opinion_1000d
model:
  activation_fn: softplus
  hidden_dim: 128
  input_dim: 1000
  num_layers: 4
  time_varying: true
training:
  batch_size: 2500
  checkpoint_dir: models/
  device: cuda:2
  learning_rate: 0.001
  n_epochs: 4000
  save_interval: 1000
