data:
  total_data: 10000
  type: gaussian1_d
model:
  activation_fn: softplus
  hidden_dim: 128
  input_dim: 50
  num_layers: 4
  time_varying: true
training:
  batch_size: 2500
  checkpoint_dir: models/
  device: cuda:3
  learning_rate: 0.001
  n_epochs: 6000
  save_interval: 1000
